name: Update README with latest blog post

on:
  schedule:
    - cron: "0 */12 * * *" # Update every 12 hours
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.4.4
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Get Latest Blog Post
        run: npm run get-latest-post

      - name: Update README
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: main
          FOLDER: .
